### ISSUE TITLE
CLI options "verbose" and "version"'s short abbreviations clash because of GetOptions is case insensitive by default

### ISSUE THREAD

**Issue by hadjiprocopis** [jozef/App-whichpm#3]
Running ```whichpm``` (of App::Whichpm v0.05, latest as of this writing) from the command line warns:

```
Duplicate specification "verbose|v" for option "v"
```
The problem is at line 53 of bin/whichpm

```
        GetOptions(
                'help|h'    => \$help,
                'quiet|q'   => \$quiet,
                'version|V' => \$version,
                'verbose|v' => \$verbose,
        ) or pod2usage;
```

With Getopt::Long version 2.57 (latest as of this writing), all options are case INSENSITIVE and therefore there is a clash between ```-V``` and ```-v```.

The remedy is to replace 
```
use Getopt::Long;
```
(in said file) with

```
use Getopt::Long qw/:config no_ignore_case/;
```

See https://metacpan.org/pod/Getopt::Long#Configuring-Getopt::Long

thanks for this module, it is really useful for me.

**Comment by jozef** [comment]
Hello @hadjiprocopis , version 0.06 with your fix was just uploaded to CPAN. Thank you for letting me know.
